# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('account', models.CharField(blank=True, max_length=255, null=True)),
                ('probability', models.FloatField(blank=True, null=True)),
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pod', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[[1, 'Pending'], [2, 'Partially Approved'], [3, 'Approved']], default='Pending')),
                ('revenue', models.FloatField(blank=True, null=True)),
                ('contract_hours', models.FloatField(blank=True, null=True)),
                ('last_modified_date', models.DateField(auto_now=True)),
                ('staff_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_manager', to=settings.AUTH_USER_MODEL)),
                ('staff_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
